### ISSUE TITLE
Shiny ink

### ISSUE THREAD

**Issue by ghost** [ZenkakuHiragana/gmod_addons#1]
For some reason, the ink is shiny. Is there a way to fix this? I'm using the splatoon sweps addon.
![20190228193248_1](https://user-images.githubusercontent.com/48101518/53587602-7fb04300-3b93-11e9-9ca1-981628ddd295.jpg)

**Comment by ZenkakuHiragana** [comment]
I couldn't reproduce the issue.
Instead, I added an option "Suppress ink refraction" to make the ink look better for you.

Also, I have some questions:
- Is the game singleplayer or not
- Any errors? (I guess probably there is no error though)
- Your DirectX level (The value of mat_dxlevel)

**Comment by ghost** [comment]
I was playing in singleplayer.
I don't have screenshots, but there were some errors about fonts and stuff.
My DirectX level is set to 95.

**Comment by ZenkakuHiragana** [comment]
Could you tell me the error message please?

**Comment by ghost** [comment]
Nevermind.
When I updated the addon, I tried shooting with the weapons but its like a machine gun, not ink.
There were alot of errors.
This is one of them.

[ERROR] addons/gmod_addons-splatoon_sweps_new/lua/splatoonsweps/shared.lua:395: attempt to call method 'GetHolstering' (a nil value)
  1. IsValidInkling - addons/gmod_addons-splatoon_sweps_new/lua/splatoonsweps/shared.lua:395
   2. v - addons/gmod_addons-splatoon_sweps_new/lua/splatoonsweps/shared.lua:15
    3. unknown - lua/includes/modules/hook.lua:84


[ERROR] addons/gmod_addons-splatoon_sweps_new/lua/weapons/weapon_splatoonsweps_shooter/shared.lua:250: attempt to call method 'GetAimTimer' (a nil value)
  1. ProtectedCall - addons/gmod_addons-splatoon_sweps_new/lua/weapons/weapon_splatoonsweps_shooter/shared.lua:250
   2. unknown - addons/gmod_addons-splatoon_sweps_new/lua/weapons/weapon_splatoonsweps_inklingbase/sh_anim.lua:59


[ERROR] addons/gmod_addons-splatoon_sweps_new/lua/splatoonsweps/shared.lua:395: attempt to call method 'GetHolstering' (a nil value)
  1. IsValidInkling - addons/gmod_addons-splatoon_sweps_new/lua/splatoonsweps/shared.lua:395
   2. v - addons/gmod_addons-splatoon_sweps_new/lua/splatoonsweps/shared.lua:10
    3. unknown - lua/includes/modules/hook.lua:84


[ERROR] addons/gmod_addons-master/lua/autorun/splatoonsweps_shared.lua:207: attempt to call method 'SetCrouchPriority' (a nil value)
  1. v - addons/gmod_addons-master/lua/autorun/splatoonsweps_shared.lua:207
   2. unknown - lua/includes/modules/hook.lua:84


[ERROR] addons/gmod_addons-master/lua/autorun/splatoonsweps_shared.lua:181: attempt to call method 'GetOnEnemyInk' (a nil value)
  1. v - addons/gmod_addons-master/lua/autorun/splatoonsweps_shared.lua:181
   2. unknown - lua/includes/modules/hook.lua:84

And when I try to change the ink color, this error pops up.


[ERROR] addons/gmod_addons-master/lua/autorun/client/splatoonsweps_userinfo.lua:155: calling 'SetInt' on bad self (attempt to modify ConVar not created by Lua)
  1. SetInt - [C]:-1
   2. OnSelect - addons/gmod_addons-master/lua/autorun/client/splatoonsweps_userinfo.lua:155
    3. ChooseOption - lua/vgui/dcombobox.lua:95
     4. DoClick - lua/vgui/dcombobox.lua:187
      5. OnMouseReleased - lua/vgui/dlabel.lua:234
       6. unknown - lua/vgui/dmenuoption.lua:77

**Comment by ZenkakuHiragana** [comment]
I guess it should have failed to initialize the weapon or the addon itself.
Could you tell me the first error message appeared in the game?
I couldn't reproduce your issue, so I need more information.

**Comment by ghost** [comment]
Ok so i found out that one of my addons were causing these errors.
After i removed the addon everything went back to normal.
I don't have time right now.
