### ISSUE TITLE
Can't use the new Splatoon SWEPs on Moray Towers?

### ISSUE THREAD

**Issue by somedoodest** [ZenkakuHiragana/gmod_addons#2]
In the latest update for the SWEPs, whenever you load up Moray Towers, it says that you're not ready to use them and to come back later. Any reason this is happening?

**Comment by ZenkakuHiragana** [comment]
It seems the addon failed to load a cache file for the map.  Try removing garrysmod/data/splatoonsweps/<map name>.txt and load the map again.
If you have played multiplayer game with the addon, try removing garrysmod/downloads/data/splatoonsweps/<map name>.txt if exists.
