### ISSUE TITLE
stranger things with hold type normal

### ISSUE THREAD

**Issue by unknown-gd** [ZenkakuHiragana/gmod_addons#4]
![image](https://user-images.githubusercontent.com/44779902/99877855-26632f80-2c12-11eb-8791-fd1db2fbeeea.png)

**Comment by ZenkakuHiragana** [comment]
I think it's not my issue.
![gm_construct0012](https://user-images.githubusercontent.com/12111138/99878539-80331c00-2c49-11eb-942f-dc2410cc6396.jpg)
