### ISSUE TITLE
(Question) The shortest path to the goal?

### ISSUE THREAD

**Issue by Shark-vil** [ZenkakuHiragana/gmod_addons#6]
Is there a function that can create the shortest path to the target, ignoring some restrictions?
I am currently using code like this:

![Code_Ezw6qLvl4d](https://user-images.githubusercontent.com/13109606/114454344-32608580-9be3-11eb-855d-ade31ef180fd.png)

I want the car to be able to follow the target along the points as close as possible to it, but the pathfinding method when using this function creates unnecessary long paths. ignoring the opportunity to turn around on the spot (since points nearby have no connection and move in a different direction)

An example of a problem:

![mpc-hc64_Q33grpjp9E](https://user-images.githubusercontent.com/13109606/114454368-38566680-9be3-11eb-8cd7-261e159da1ed.png)

Is there a function or code snippet that can do what I need? :)

[I apologize for the duplicate question in the Steam discussions](https://steamcommunity.com/workshop/filedetails/discussion/1587455087/3168820451549463699/)

**Comment by ZenkakuHiragana** [comment]
Basically you can't, but I think it's possible by the following steps: 1. place some helper waypoints with a specific group number.  2. set the third argument of `DecentVehicleDestination.GetRoute()` to it when the car needs a shortcut.

**Comment by Shark-vil** [comment]
> Basically you can't, but I think it's possible by the following steps: 1. place some helper waypoints with a specific group number. 2. set the third argument of `DecentVehicleDestination.GetRoute()` to it when the car needs a shortcut.

Okay, I'll check it out. Thanks for the answer.
